### ISSUE TITLE
Other Aosp apps?

### ISSUE THREAD

**Issue by TheSilencedOne** [qw123wh/Aospdeskclock#3]
Great clock app been looking for stock Aosp apps that work on all devices, will you be making any other Aosp apps in the future?
(I really am just look for a good Aosp calculator & calendar)

**Comment by qw123wh** [comment]
I don't know if i will bring other aosp apps, however as good calculators i can recommend these:

https://github.com/Javinator9889/calculator

https://github.com/SimpleMobileTools/Simple-Calculator

https://github.com/tranleduy2000/ncalc


for the calendar I can recommend you etar (which is based on the aosp calendar)

https://github.com/Etar-Group/Etar-Calendar

Or 

https://github.com/SimpleMobileTools/Simple-Calendar

**Comment by qw123wh** [comment]
if you want you can try the calculator https://github.com/qw123wh/Aosp-Calulator/tree/0.1

**Comment by mariobrostech** [comment]
@qw123wh

Sorry to bother you, but I wanted to also share my opinion. I think you should really consider doing this with other stock AOSP apps if you have the time to do so because while there are many third-party options available, most of them lack functionality or stability when compared to their Google-made counterparts. This would be really cool, and I'd happily make a small donation (and I'm sure others would as well) as an incentive to having you do this.

Having these apps compiled with their proprietary blobs removed and published on F-Droid would be a game-changer for me personally. I don't know much about Android development, though, so if you think this is unrealistic, I completely understand. This is coming purely from a user's perspective.

Let me know your thoughts, and thanks in advance for your consideration!
